### ISSUE TITLE
Add link to associated publication(s)

### ISSUE THREAD

**Issue by davisjam** [NicolaasWeideman/RegexStaticAnalysis#2]
It's not entirely clear to me what publication(s) are associated with this project.

Looks like it is (at least) one of the following:
- "Turning Evil Regexes Harmless"
- "Analyzing Catastrophic Backtracking Behavior in Practical Regular Expression Matching"
- "Analyzing matching time behavior of backtracking regular expression matchers by using ambiguity of NFA"

Sticking a note in the README would be nice.

**Comment by NicolaasWeideman** [comment]
Thanks for the suggestion, I added the links.

**Comment by davisjam** [comment]
Great, thanks.
